World properties, "chat" always emits even with prefix
Anatoly03/pixelwalker.js pull request #14
Opened 2024-04-30 15:04 UTC by ConnorMcGehee

2024-04-30 19:56 UTC, Anatoly03 requested changes
Change of world properties is questionable.

2024-04-30 19:56 UTC, Anatoly03 commented on package.json
> +    "dotenv": "^16.4.5",
This is not supposed to be part of the API itself.

2024-04-30 19:56 UTC, Anatoly03 commented on src/events.ts
> +        client.world = new World(id, cuid, username, face, isAdmin, x, y, can_edit, can_god, title, plays, owner, global_switch_states, width, height)
World is not supposed to track this information.

2024-04-30 20:05 UTC, ConnorMcGehee commented
Oops ignore the dotenv

I do think world properties should be tracked though, where would you say is better?

2024-05-01 06:15 UTC, Anatoly03 commented
If you want, you can provide `World` with a public variable`: Player` and set it upon init in events.

2024-05-01 06:47 UTC, Anatoly03 commented
If you want, you can also wait a bit, I’m currently in the process of rebuilding the internal structure of the API in regards to `World`. We could discuss it on Discord and put our effort together.

2024-05-01 07:09 UTC, Anatoly03 commented on package.json
> +    "dotenv": "^16.4.5",
```suggestion
```

2024-05-01 09:10 UTC, Anatoly03 commented
Sorry for the conflicts 😢

2024-05-01 15:31 UTC, Anatoly03 commented
Chat added in https://github.com/Anatoly03/pixelwalker.js/pull/16

2024-05-01 18:28 UTC, closed without merging